### PR TITLE
test: add transport compliance tests

### LINKED ISSUE #1836: Run transport compliance tests

### PR DESCRIPTION
**Pull request by maschad**
Closes https://github.com/libp2p/js-libp2p/issues/1836

### CODE REVIEW

**Comment by p-shahi** [comment]
This is unblocked now right?

**Comment by dhuseby** [comment]
is this a flakey test that needs investigating still?

**Comment by maschad** [comment]
> is this a flakey test that needs investigating still?

No @dhuseby , actually there is some refactoring work that is being done on the [compliance tests](https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/interface-transport-compliance-tests#readme) in order to land this. @achingbrain can expound

**Comment by BigLep** [comment]
> No @dhuseby , actually there is some refactoring work that is being done on the [compliance tests](https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/interface-transport-compliance-tests#readme) in order to land this. 

Is there a tracking issue for this work that is blocking this?  I'm asking so know where to follow along.

**Comment by dhuseby** [comment]
I want to echo @BigLep 's request. @achingbrain is there a tracking issue for what's blocking this PR?

**Comment by p-shahi** [comment]
We discussed this in the js-libp2p maintainers call on 2023-06-06, this is parked until some tech debt related to compliance test refactoring is landed. Issue for that created here: https://github.com/libp2p/js-libp2p/issues/1852
As of 2023-06-06 that refactoring work hasn't been pushed as a draft to GitHub.
This branch doesn't have a whole lot going on it and though it's a draft, it's getting some traffic. Therefore, I'll close this until https://github.com/libp2p/js-libp2p/issues/1852 is resolved

**Pull request closed without merging**
