### PR TITLE
refactor: remove use of timeout-abort-controller

### PR DESCRIPTION
**Pull request by maschad**
related https://github.com/libp2p/js-libp2p/issues/1681

### CODE REVIEW

**Review by MarcoPolo — APPROVED** [review]

**Comment by MarcoPolo** [comment]
CI is failing though?

**Comment by maschad** [comment]
> CI is failing though?

It's a bit strange that a lack of tests would cause [an error](https://github.com/libp2p/js-libp2p-webrtc/actions/runs/4853987162/jobs/8650811364?pr=148#step:9:32) and I am noticing it on other [PRs](https://github.com/libp2p/js-libp2p-webrtc/actions/runs/4821978491/jobs/8589809711?pr=71#step:9:32) looks like an issue with playwright

**Comment by MarcoPolo** [comment]
yeah, I fixed it in #109

**Comment by MarcoPolo** [comment]
let me merge that one, then you can merge master/rebase and get passing tests.

**Pull request merged**
